/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/address/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode */
        get: operations["geocode_v1_address_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/address/pobox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pobox */
        get: operations["pobox_v1_address_pobox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/address/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reverse Geocode */
        get: operations["reverse_geocode_v1_address_reverse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/address/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_address_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/address/zipcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zipcode */
        get: operations["zipcode_v1_address_zipcode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/cache/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cache Metrics */
        get: operations["cache_metrics_v1_admin_cache_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/consistency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Consistency */
        get: operations["list_consistency_v1_admin_consistency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/consistency/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Consistency */
        post: operations["run_consistency_v1_admin_consistency_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/consistency/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consistency Report */
        get: operations["consistency_report_v1_admin_consistency__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain */
        post: operations["explain_v1_admin_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_v1_admin_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_v1_admin_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_v1_admin_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/load-sources/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover Load Source Set */
        post: operations["discover_load_source_set_v1_admin_load_sources_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/load-sources/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Load Source Set */
        post: operations["plan_load_source_set_v1_admin_load_sources_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/loads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Loads */
        get: operations["list_loads_v1_admin_loads_get"];
        put?: never;
        /** Submit Load */
        post: operations["submit_load_v1_admin_loads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/loads/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Status */
        get: operations["load_status_v1_admin_loads__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/loads/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Load */
        post: operations["cancel_load_v1_admin_loads__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Logs */
        get: operations["recent_logs_v1_admin_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/maintenance/refresh-mv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Mv */
        post: operations["refresh_mv_v1_admin_maintenance_refresh_mv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/normalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Normalize */
        post: operations["normalize_v1_admin_normalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ops/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ops Artifacts */
        get: operations["list_ops_artifacts_v1_admin_ops_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ops/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ops Audit Events */
        get: operations["list_ops_audit_events_v1_admin_ops_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ops/maintenance-windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ops Maintenance Windows */
        get: operations["list_ops_maintenance_windows_v1_admin_ops_maintenance_windows_get"];
        put?: never;
        /** Create Ops Maintenance Window */
        post: operations["create_ops_maintenance_window_v1_admin_ops_maintenance_windows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ops/maintenance-windows/{window_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Ops Maintenance Window */
        post: operations["end_ops_maintenance_window_v1_admin_ops_maintenance_windows__window_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ops/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ops Releases */
        get: operations["list_ops_releases_v1_admin_ops_releases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ops/releases/{release_id}/rollback-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback Plan */
        post: operations["rollback_plan_v1_admin_ops_releases__release_id__rollback_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ops/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ops Snapshots */
        get: operations["list_ops_snapshots_v1_admin_ops_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ops/table-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ops Table Stats */
        get: operations["list_ops_table_stats_v1_admin_ops_table_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ops/table-stats/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Ops Table Stats */
        post: operations["capture_ops_table_stats_v1_admin_ops_table_stats_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Table Stats */
        get: operations["table_stats_v1_admin_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/upload/sido-zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Sido Zip */
        post: operations["upload_sido_zip_v1_admin_upload_sido_zip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload Session */
        post: operations["create_upload_session_v1_admin_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/uploads/{upload_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upload Session Status */
        get: operations["upload_session_status_v1_admin_uploads__upload_set_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/uploads/{upload_set_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Upload Session */
        post: operations["cancel_upload_session_v1_admin_uploads__upload_set_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/uploads/{upload_set_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Upload File */
        put: operations["put_upload_file_v1_admin_uploads__upload_set_id__files_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddressStructure
         * @description Structured address fields using vworld-compatible names.
         */
        AddressStructure: {
            /** Detail */
            detail?: string | null;
            /**
             * Level0
             * @default 대한민국
             */
            level0: string;
            /** Level1 */
            level1?: string | null;
            /** Level2 */
            level2?: string | null;
            /** Level3 */
            level3?: string | null;
            /** Level4A */
            level4A?: string | null;
            /** Level4Ac */
            level4AC?: string | null;
            /** Level4L */
            level4L?: string | null;
            /** Level4Lc */
            level4LC?: string | null;
            /** Level5 */
            level5?: string | null;
        };
        /** @enum {string} */
        AddressType: "road" | "parcel";
        /** AuditEvent */
        AuditEvent: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id?: string | null;
            /**
             * Actor Type
             * @enum {string}
             */
            actor_type: "system" | "cli" | "api" | "ui" | "scheduler";
            /** Client Ip Hash */
            client_ip_hash?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Event Id */
            event_id: string;
            /** Job Id */
            job_id?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "started" | "succeeded" | "failed" | "cancelled" | "denied";
            /** Payload Hash */
            payload_hash: string;
            /** Payload Redacted */
            payload_redacted?: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id?: string | null;
            /** Resource Id */
            resource_id?: string | null;
            /** Resource Type */
            resource_type?: string | null;
            /** Trace Id */
            trace_id?: string | null;
            /** User Agent Hash */
            user_agent_hash?: string | null;
        };
        /** BBox */
        BBox: {
            /** Max X */
            max_x: number;
            /** Max Y */
            max_y: number;
            /** Min X */
            min_x: number;
            /** Min Y */
            min_y: number;
        };
        /** @description Coordinate reference system normalized as EPSG:XXXX */
        CRS: string;
        /** CacheMetrics */
        CacheMetrics: {
            /** Enabled */
            enabled: boolean;
            /** Entries */
            entries: number;
            /** Expired */
            expired: number;
            /** Hits */
            hits: number;
        };
        /** ConsistencyCase */
        ConsistencyCase: {
            /** Code */
            code: string;
            /** Count */
            count: number;
            /** Metric */
            metric?: {
                [key: string]: number;
            } | null;
            /** Name */
            name: string;
            /** Note */
            note?: string | null;
            /** Ratio */
            ratio?: number | null;
            /**
             * Sample
             * @default []
             */
            sample: {
                [key: string]: unknown;
            }[];
            /**
             * Severity
             * @enum {string}
             */
            severity: "OK" | "INFO" | "WARN" | "ERROR";
            /** Threshold */
            threshold?: string | null;
        };
        /** ConsistencyReport */
        ConsistencyReport: {
            /**
             * Cases
             * @default []
             */
            cases: components["schemas"]["ConsistencyCase"][];
            /** Finished At */
            finished_at?: string | null;
            /**
             * Generated By
             * @default api
             * @enum {string}
             */
            generated_by: "cli" | "api" | "cron";
            /** Report Id */
            report_id: string;
            /** Scope */
            scope: string;
            /**
             * Severity Max
             * @enum {string}
             */
            severity_max: "OK" | "INFO" | "WARN" | "ERROR";
            /** Source Set */
            source_set: {
                [key: string]: string;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** ConsistencyReportSummary */
        ConsistencyReportSummary: {
            /** Finished At */
            finished_at?: string | null;
            /**
             * Generated By
             * @default api
             * @enum {string}
             */
            generated_by: "cli" | "api" | "cron";
            /** Report Id */
            report_id: string;
            /** Scope */
            scope: string;
            /**
             * Severity Max
             * @enum {string}
             */
            severity_max: "OK" | "INFO" | "WARN" | "ERROR";
            /** Source Set */
            source_set: {
                [key: string]: string;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** ConsistencyRunRequest */
        ConsistencyRunRequest: {
            /** Cases */
            cases?: string[] | null;
            /**
             * Recent Days
             * @default 7
             */
            recent_days: number;
            /**
             * Scope
             * @default full
             * @enum {string}
             */
            scope: "full" | "sido" | "recent";
            /** Sido */
            sido?: string | null;
        };
        /** DatasetSnapshot */
        DatasetSnapshot: {
            /** Alembic Revision */
            alembic_revision?: string | null;
            /** Backup Artifact Id */
            backup_artifact_id?: string | null;
            /** Consistency Report Id */
            consistency_report_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Job Id */
            created_by_job_id?: string | null;
            /** Git Commit */
            git_commit?: string | null;
            /** Parent Snapshot Id */
            parent_snapshot_id?: string | null;
            /** Performance Artifact Id */
            performance_artifact_id?: string | null;
            /** Postgis Version */
            postgis_version?: string | null;
            /** Postgres Version */
            postgres_version?: string | null;
            /** Row Counts */
            row_counts?: {
                [key: string]: number;
            };
            /** Snapshot Id */
            snapshot_id: string;
            /** Source Set */
            source_set?: {
                [key: string]: unknown;
            };
            /** Source Set Hash */
            source_set_hash: string;
            /**
             * State
             * @enum {string}
             */
            state: "building" | "validated" | "rejected" | "released" | "retired";
            /** Table Stats Artifact Id */
            table_stats_artifact_id?: string | null;
            /** Validated At */
            validated_at?: string | null;
        };
        /** ExplainRequest */
        ExplainRequest: {
            /**
             * Analyze
             * @default false
             */
            analyze: boolean;
            /**
             * Buffers
             * @default false
             */
            buffers: boolean;
            /** Sql */
            sql: string;
        };
        /** ExplainResponse */
        ExplainResponse: {
            /** Plan */
            plan: unknown;
        };
        /** GeocodeExtension */
        GeocodeExtension: {
            /** Bd Mgt Sn */
            bd_mgt_sn?: string | null;
            /** Bjd Cd */
            bjd_cd?: string | null;
            /** Buld Nm */
            buld_nm?: string | null;
            /** Confidence */
            confidence: number;
            /** Rncode Full */
            rncode_full?: string | null;
            /** @default local */
            source: components["schemas"]["ResultSource"];
            /** Zip No */
            zip_no?: string | null;
            zip_source?: components["schemas"]["ZipSource"] | null;
        };
        /** GeocodeInput */
        GeocodeInput: {
            /** Address */
            address: string;
            /** @default EPSG:4326 */
            crs: components["schemas"]["CRS"];
            /**
             * Fallback
             * @default local_only
             * @enum {string}
             */
            fallback: "off" | "local_only" | "api";
            /**
             * Refine
             * @default true
             */
            refine: boolean;
            /**
             * Simple
             * @default false
             */
            simple: boolean;
            /** @default road */
            type: components["schemas"]["AddressType"];
        };
        /** GeocodeResponse */
        GeocodeResponse: {
            input: components["schemas"]["GeocodeInput"];
            refined?: components["schemas"]["RefinedAddress"] | null;
            result?: components["schemas"]["GeocodeResult"] | null;
            service: components["schemas"]["ServiceMeta"];
            status: components["schemas"]["Status"];
            x_extension?: components["schemas"]["GeocodeExtension"] | null;
        };
        /** GeocodeResult */
        GeocodeResult: {
            /** @default EPSG:4326 */
            crs: components["schemas"]["CRS"];
            point: components["schemas"]["Point"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoadJobStatus */
        LoadJobStatus: {
            /** Current Stage */
            current_stage?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: ("full_load_batch" | "juso_text_load" | "daily_juso_delta" | "juso_parcel_link_load" | "juso_parcel_link_delta" | "roadaddr_entrance_load" | "locsum_load" | "navi_load" | "shp_polygons_load" | "shp_polygons_delta" | "pobox_load" | "bulk_load" | "mv_refresh" | "consistency_check") | string;
            /** Load Batch Id */
            load_batch_id?: string | null;
            /**
             * Log Tail
             * @default []
             */
            log_tail: string[];
            /** Parent Job Id */
            parent_job_id?: string | null;
            /** Payload Summary */
            payload_summary?: {
                [key: string]: unknown;
            } | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Source Set */
            source_set?: {
                [key: string]: string;
            } | null;
            /** Source Yyyymm */
            source_yyyymm?: string | null;
            /** Started At */
            started_at?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "failed" | "cancelled";
        };
        /** LoadSubmitRequest */
        LoadSubmitRequest: {
            /** Kind */
            kind: ("full_load_batch" | "juso_text_load" | "daily_juso_delta" | "juso_parcel_link_load" | "juso_parcel_link_delta" | "roadaddr_entrance_load" | "locsum_load" | "navi_load" | "shp_polygons_load" | "shp_polygons_delta" | "pobox_load" | "bulk_load" | "mv_refresh" | "consistency_check") | string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** MaintenanceWindow */
        MaintenanceWindow: {
            /** Actual Ended At */
            actual_ended_at?: string | null;
            /** Actual Started At */
            actual_started_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Blocks */
            blocks?: {
                [key: string]: unknown;
            };
            /** Closed By Job Id */
            closed_by_job_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Job Id */
            created_by_job_id?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "full_load" | "restore" | "schema_migration" | "mv_refresh" | "read_only" | "exclusive";
            /** Reason */
            reason: string;
            /** Requested By */
            requested_by?: string | null;
            /** Starts At */
            starts_at?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "scheduled" | "active" | "ending" | "ended" | "cancelled" | "failed";
            /** Window Id */
            window_id: string;
        };
        /** MaintenanceWindowCreate */
        MaintenanceWindowCreate: {
            /** Approved By */
            approved_by?: string | null;
            /** Blocks */
            blocks?: {
                [key: string]: unknown;
            };
            /** Confirmation */
            confirmation: string;
            /** Created By Job Id */
            created_by_job_id?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "full_load" | "restore" | "schema_migration" | "mv_refresh" | "read_only" | "exclusive";
            /** Reason */
            reason: string;
            /** Requested By */
            requested_by?: string | null;
            /** Starts At */
            starts_at?: string | null;
        };
        /** MaintenanceWindowEnd */
        MaintenanceWindowEnd: {
            /** Closed By Job Id */
            closed_by_job_id?: string | null;
            /** Confirmation */
            confirmation: string;
        };
        /** NormalizeRequest */
        NormalizeRequest: {
            /** Address */
            address: string;
        };
        /** NormalizeResponse */
        NormalizeResponse: {
            /** Normalized */
            normalized: string;
            /** Original */
            original: string;
            /**
             * Tokens
             * @default []
             */
            tokens: string[];
        };
        /** OpsArtifact */
        OpsArtifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Artifact Type */
            artifact_type: string;
            /** Callback State */
            callback_state?: string | null;
            /** Callback Url */
            callback_url?: string | null;
            /** Compression */
            compression?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Job Id */
            job_id?: string | null;
            /** Manifest */
            manifest?: {
                [key: string]: unknown;
            };
            /** Media Type */
            media_type?: string | null;
            /** Release Id */
            release_id?: string | null;
            /** Retention Class */
            retention_class?: string | null;
            /** Sha256 */
            sha256?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Snapshot Id */
            snapshot_id?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "creating" | "available" | "failed" | "deleted" | "expired";
            /**
             * Storage Kind
             * @enum {string}
             */
            storage_kind: "local_file" | "s3" | "gcs" | "none";
            /** Storage Uri */
            storage_uri?: string | null;
        };
        /** PoboxInput */
        PoboxInput: {
            /**
             * Kind
             * @default ALL
             * @enum {string}
             */
            kind: "PO" | "PG" | "ALL";
            /**
             * Page
             * @default 1
             */
            page: number;
            /** Query */
            query?: string | null;
            /** Sgg Nm */
            sgg_nm?: string | null;
            /** Si Nm */
            si_nm?: string | null;
            /**
             * Size
             * @default 10
             */
            size: number;
        };
        /** PoboxResponse */
        PoboxResponse: {
            input: components["schemas"]["PoboxInput"];
            /**
             * Result
             * @default []
             */
            result: components["schemas"]["PoboxResultItem"][];
            service: components["schemas"]["ServiceMeta"];
            status: components["schemas"]["Status"];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** PoboxResultItem */
        PoboxResultItem: {
            /** Bjd Cd */
            bjd_cd?: string | null;
            /** Emd Nm */
            emd_nm?: string | null;
            /**
             * Pobox Kind
             * @enum {string}
             */
            pobox_kind: "PO" | "PG";
            /** Pobox Name */
            pobox_name?: string | null;
            /** Pobox No Mn */
            pobox_no_mn?: number | null;
            /** Pobox No Sl */
            pobox_no_sl?: number | null;
            /** Sgg Nm */
            sgg_nm?: string | null;
            /** Si Nm */
            si_nm?: string | null;
            /** Zip No */
            zip_no: string;
        };
        /**
         * Point
         * @description Coordinate point. External interfaces use ``x=lon`` and ``y=lat``.
         */
        Point: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** RefinedAddress */
        RefinedAddress: {
            structure: components["schemas"]["AddressStructure"];
            /** Text */
            text: string;
        };
        /** @enum {string} */
        ResultSource: "local" | "api_juso" | "api_vworld" | "cache";
        /** ReverseInput */
        ReverseInput: {
            /** @default EPSG:4326 */
            crs: components["schemas"]["CRS"];
            point: components["schemas"]["Point"];
            /**
             * Radius M
             * @default 200
             */
            radius_m: number;
            /**
             * Type
             * @default both
             * @enum {string}
             */
            type: "both" | "road" | "parcel";
            /**
             * Zipcode
             * @default true
             */
            zipcode: boolean;
        };
        /** ReverseResponse */
        ReverseResponse: {
            input: components["schemas"]["ReverseInput"];
            /**
             * Result
             * @default []
             */
            result: components["schemas"]["ReverseResultItem"][];
            service: components["schemas"]["ServiceMeta"];
            status: components["schemas"]["Status"];
        };
        /** ReverseResultItem */
        ReverseResultItem: {
            /** Distance M */
            distance_m?: number | null;
            point?: components["schemas"]["Point"] | null;
            /** @default local */
            source: components["schemas"]["ResultSource"];
            structure: components["schemas"]["AddressStructure"];
            /** Text */
            text: string;
            type: components["schemas"]["AddressType"];
            zip_source?: components["schemas"]["ZipSource"] | null;
            /** Zipcode */
            zipcode?: string | null;
        };
        /** RollbackPlan */
        RollbackPlan: {
            /**
             * Blockers
             * @default []
             */
            blockers: string[];
            /** Release Id */
            release_id: string;
            /**
             * Requires Maintenance Window
             * @default true
             */
            requires_maintenance_window: boolean;
            /** Snapshot Id */
            snapshot_id: string;
            /**
             * Steps
             * @default []
             */
            steps: string[];
            /** Typed Confirmation */
            typed_confirmation: string;
        };
        /** SearchInput */
        SearchInput: {
            bbox?: components["schemas"]["BBox"] | null;
            /** Category */
            category?: string | null;
            /** @default EPSG:4326 */
            crs: components["schemas"]["CRS"];
            /**
             * Page
             * @default 1
             */
            page: number;
            /** Query */
            query: string;
            /**
             * Size
             * @default 10
             */
            size: number;
            /**
             * Type
             * @default address
             * @enum {string}
             */
            type: "address" | "place" | "district" | "road";
        };
        /** SearchResponse */
        SearchResponse: {
            input: components["schemas"]["SearchInput"];
            /**
             * Result
             * @default []
             */
            result: components["schemas"]["SearchResultItem"][];
            service: components["schemas"]["ServiceMeta"];
            status: components["schemas"]["Status"];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** SearchResultItem */
        SearchResultItem: {
            /** Address */
            address?: string | null;
            point?: components["schemas"]["Point"] | null;
            /** Score */
            score?: number | null;
            /** @default local */
            source: components["schemas"]["ResultSource"];
            structure?: components["schemas"]["AddressStructure"] | null;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "address" | "place" | "district" | "road";
        };
        /** ServiceMeta */
        ServiceMeta: {
            /** Name */
            name: string;
            /** Operation */
            operation: string;
            /** Time */
            time?: string | null;
            /**
             * Version
             * @default 2.0
             */
            version: string;
        };
        /** ServingRelease */
        ServingRelease: {
            /** Activated At */
            activated_at?: string | null;
            /** Activated By Job Id */
            activated_by_job_id?: string | null;
            /** Consistency Gate */
            consistency_gate?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Mv Hash */
            mv_hash?: string | null;
            /**
             * Mv Name
             * @default mv_geocode_target
             */
            mv_name: string;
            /** Notes */
            notes?: string | null;
            /** Performance Gate */
            performance_gate?: {
                [key: string]: unknown;
            };
            /** Previous Release Id */
            previous_release_id?: string | null;
            /** Release Id */
            release_id: string;
            /**
             * Release Kind
             * @enum {string}
             */
            release_kind: "full_load" | "daily_delta" | "restore" | "manual_rebuild" | "rollback";
            /** Rollback Target Release Id */
            rollback_target_release_id?: string | null;
            /** Snapshot Id */
            snapshot_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "active" | "superseded" | "rolled_back" | "failed";
        };
        /** SourceCandidate */
        SourceCandidate: {
            /** Byte Size */
            byte_size?: number | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** File Count */
            file_count?: number | null;
            /** Inferred Yyyymm */
            inferred_yyyymm?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "juso" | "parcel_link" | "locsum" | "navi" | "shp" | "roadaddr_entrance" | "sppn_makarea" | "pobox" | "bulk";
            /** Note */
            note?: string | null;
            /** Path */
            path: string;
            /** Sha256 */
            sha256?: string | null;
            /** Sido Count */
            sido_count?: number | null;
        };
        /** SourceSetDiscovery */
        SourceSetDiscovery: {
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["SourceCandidate"][];
            /**
             * Missing Required
             * @default []
             */
            missing_required: string[];
            /**
             * Mixed Yyyymm
             * @default false
             */
            mixed_yyyymm: boolean;
            /** Recommended */
            recommended?: {
                [key: string]: components["schemas"]["SourceCandidate"];
            };
            /** Root Path */
            root_path: string;
            /** Warning */
            warning?: string | null;
            /** Yyyymm By Kind */
            yyyymm_by_kind?: {
                [key: string]: string | null;
            };
        };
        /** SourceSetDiscoveryRequest */
        SourceSetDiscoveryRequest: {
            /**
             * Include Optional
             * @default true
             */
            include_optional: boolean;
            /** Root Path */
            root_path?: string | null;
            /** Upload Set Id */
            upload_set_id?: string | null;
        };
        /** SourceSetPlan */
        SourceSetPlan: {
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** Acknowledged By */
            acknowledged_by?: ("cli" | "api" | "ui") | null;
            /** Batch Payload */
            batch_payload?: {
                [key: string]: unknown;
            };
            /** Candidate Paths */
            candidate_paths?: {
                [key: string]: string;
            };
            /** Candidate Sha256 */
            candidate_sha256?: {
                [key: string]: string | null;
            };
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["SourceCandidate"][];
            /** Confirmation Token Hash */
            confirmation_token_hash?: string | null;
            /** Expected Confirmation Token */
            expected_confirmation_token?: string | null;
            /**
             * Missing Required
             * @default []
             */
            missing_required: string[];
            /**
             * Mixed Yyyymm
             * @default false
             */
            mixed_yyyymm: boolean;
            /**
             * Mixed Yyyymm Acknowledged
             * @default false
             */
            mixed_yyyymm_acknowledged: boolean;
            /** Root Path */
            root_path?: string | null;
            /** Selected */
            selected?: {
                [key: string]: components["schemas"]["SourceCandidate"];
            };
            /** Source Set Id */
            source_set_id: string;
            /** Warning */
            warning?: string | null;
            /** Yyyymm By Kind */
            yyyymm_by_kind?: {
                [key: string]: string | null;
            };
        };
        /** SourceSetPlanRequest */
        SourceSetPlanRequest: {
            /**
             * Acknowledged By
             * @default api
             * @enum {string}
             */
            acknowledged_by: "cli" | "api" | "ui";
            /**
             * Allow Mixed Yyyymm
             * @default false
             */
            allow_mixed_yyyymm: boolean;
            /** Confirmation Token */
            confirmation_token?: string | null;
            /** Explicit Paths */
            explicit_paths?: {
                [key: string]: string;
            };
            /**
             * Include Optional
             * @default true
             */
            include_optional: boolean;
            /** Root Path */
            root_path?: string | null;
            /** Upload Set Id */
            upload_set_id?: string | null;
            /** Versions */
            versions?: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        Status: "OK" | "NOT_FOUND" | "ERROR";
        /** TableStat */
        TableStat: {
            /** Row Count */
            row_count: number;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Table Name */
            table_name: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** TableStatsSnapshot */
        TableStatsSnapshot: {
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Dead Tuples */
            dead_tuples?: number | null;
            /** Estimated Rows */
            estimated_rows?: number | null;
            /** Exact Rows */
            exact_rows?: number | null;
            /** Index Bytes */
            index_bytes?: number | null;
            /** Last Analyze */
            last_analyze?: string | null;
            /** Last Vacuum */
            last_vacuum?: string | null;
            /**
             * Object Kind
             * @enum {string}
             */
            object_kind: "table" | "materialized_view" | "index" | "toast" | "other";
            /** Object Name */
            object_name: string;
            /** Schema Name */
            schema_name: string;
            /** Snapshot Id */
            snapshot_id?: string | null;
            /** Stats */
            stats?: {
                [key: string]: unknown;
            };
            /** Stats Id */
            stats_id: string;
            /** Table Bytes */
            table_bytes?: number | null;
            /** Toast Bytes */
            toast_bytes?: number | null;
            /** Total Bytes */
            total_bytes?: number | null;
        };
        /** UploadFileStatus */
        UploadFileStatus: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Message */
            error_message?: string | null;
            /** File Id */
            file_id: string;
            /** Filename */
            filename: string;
            /** Inferred Yyyymm */
            inferred_yyyymm?: string | null;
            /** Path */
            path: string;
            /** Relative Path */
            relative_path?: string | null;
            /** Sha256 */
            sha256?: string | null;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /** Source Kind */
            source_kind?: ("juso" | "parcel_link" | "locsum" | "navi" | "shp" | "roadaddr_entrance" | "sppn_makarea" | "pobox" | "bulk") | null;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "uploading" | "uploaded" | "cancelled" | "failed";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Upload Set Id */
            upload_set_id: string;
            /**
             * Uploaded Bytes
             * @default 0
             */
            uploaded_bytes: number;
        };
        /** UploadSetCreateRequest */
        UploadSetCreateRequest: {
            /**
             * Purpose
             * @default full_load_source_set
             * @constant
             */
            purpose: "full_load_source_set";
        };
        /** UploadSetStatus */
        UploadSetStatus: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Message */
            error_message?: string | null;
            /**
             * Files
             * @default []
             */
            files: components["schemas"]["UploadFileStatus"][];
            /** Purpose */
            purpose: string;
            /** Root Path */
            root_path: string;
            /**
             * State
             * @enum {string}
             */
            state: "created" | "uploading" | "uploaded" | "cancelled" | "failed";
            /**
             * Total Bytes
             * @default 0
             */
            total_bytes: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Upload Set Id */
            upload_set_id: string;
            /**
             * Uploaded Bytes
             * @default 0
             */
            uploaded_bytes: number;
        };
        /** UploadSidoZipResponse */
        UploadSidoZipResponse: {
            /** Filename */
            filename: string;
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Upload Id */
            upload_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ZipSource
         * @enum {string}
         */
        ZipSource: "building_bsi_zon_no" | "bulk_delivery" | "kodis_bas_within" | "kodis_bas_centroid" | "pobox";
        /** ZipcodeInput */
        ZipcodeInput: {
            /** Address */
            address?: string | null;
            /** Bd Mgt Sn */
            bd_mgt_sn?: string | null;
            /**
             * Include Bulk
             * @default true
             */
            include_bulk: boolean;
            point?: components["schemas"]["Point"] | null;
        };
        /** ZipcodeResponse */
        ZipcodeResponse: {
            input: components["schemas"]["ZipcodeInput"];
            /**
             * Result
             * @default []
             */
            result: components["schemas"]["ZipcodeResultItem"][];
            service: components["schemas"]["ServiceMeta"];
            status: components["schemas"]["Status"];
        };
        /** ZipcodeResultItem */
        ZipcodeResultItem: {
            /** Address */
            address?: string | null;
            /** Bd Mgt Sn */
            bd_mgt_sn?: string | null;
            /** Detail */
            detail?: string | null;
            source: components["schemas"]["ZipSource"];
            /** Zip No */
            zip_no: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    geocode_v1_address_geocode_get: {
        parameters: {
            query: {
                address: string;
                type?: "road" | "parcel";
                crs?: string;
                refine?: boolean;
                simple?: boolean;
                fallback?: "off" | "local_only" | "api";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pobox_v1_address_pobox_get: {
        parameters: {
            query?: {
                query?: string | null;
                si_nm?: string | null;
                sgg_nm?: string | null;
                kind?: "PO" | "PG" | "ALL";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoboxResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reverse_geocode_v1_address_reverse_get: {
        parameters: {
            query: {
                x: number;
                y: number;
                crs?: string;
                type?: "both" | "road" | "parcel";
                zipcode?: boolean;
                radius_m?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReverseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_address_search_get: {
        parameters: {
            query: {
                query: string;
                type?: "address" | "place" | "district" | "road";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zipcode_v1_address_zipcode_get: {
        parameters: {
            query?: {
                address?: string | null;
                x?: number | null;
                y?: number | null;
                bd_mgt_sn?: string | null;
                include_bulk?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZipcodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cache_metrics_v1_admin_cache_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheMetrics"];
                };
            };
        };
    };
    list_consistency_v1_admin_consistency_get: {
        parameters: {
            query?: {
                limit?: number;
                severity_at_least?: ("INFO" | "WARN" | "ERROR") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsistencyReportSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_consistency_v1_admin_consistency_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsistencyRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consistency_report_v1_admin_consistency__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsistencyReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_v1_admin_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_v1_admin_jobs_get: {
        parameters: {
            query?: {
                kind?: string | null;
                state?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadJobStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_v1_admin_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_v1_admin_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_load_source_set_v1_admin_load_sources_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceSetDiscoveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSetDiscovery"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_load_source_set_v1_admin_load_sources_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceSetPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSetPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_loads_v1_admin_loads_get: {
        parameters: {
            query?: {
                kind?: string | null;
                state?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadJobStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_load_v1_admin_loads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_status_v1_admin_loads__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_load_v1_admin_loads__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_logs_v1_admin_logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_mv_v1_admin_maintenance_refresh_mv_post: {
        parameters: {
            query?: {
                strategy?: "concurrent" | "swap";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    normalize_v1_admin_normalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NormalizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NormalizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_artifacts_v1_admin_ops_artifacts_get: {
        parameters: {
            query?: {
                limit?: number;
                artifact_type?: string | null;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsArtifact"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_audit_events_v1_admin_ops_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
                action?: string | null;
                outcome?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_maintenance_windows_v1_admin_ops_maintenance_windows_get: {
        parameters: {
            query?: {
                limit?: number;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceWindow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ops_maintenance_window_v1_admin_ops_maintenance_windows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceWindowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceWindow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_ops_maintenance_window_v1_admin_ops_maintenance_windows__window_id__end_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                window_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceWindowEnd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceWindow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_releases_v1_admin_ops_releases_get: {
        parameters: {
            query?: {
                limit?: number;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServingRelease"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_plan_v1_admin_ops_releases__release_id__rollback_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollbackPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_snapshots_v1_admin_ops_snapshots_get: {
        parameters: {
            query?: {
                limit?: number;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_table_stats_v1_admin_ops_table_stats_get: {
        parameters: {
            query?: {
                limit?: number;
                snapshot_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableStatsSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_ops_table_stats_v1_admin_ops_table_stats_capture_post: {
        parameters: {
            query?: {
                snapshot_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableStatsSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    table_stats_v1_admin_tables_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableStat"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_sido_zip_v1_admin_upload_sido_zip_post: {
        parameters: {
            query: {
                filename: string;
                sido?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSidoZipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_session_v1_admin_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSetCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSetStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_session_status_v1_admin_uploads__upload_set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSetStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_upload_session_v1_admin_uploads__upload_set_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSetStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_upload_file_v1_admin_uploads__upload_set_id__files_put: {
        parameters: {
            query: {
                filename: string;
                relative_path?: string | null;
            };
            header?: never;
            path: {
                upload_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadFileStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
