"""C1~C10 consistency case definitions shared by admin API and UI."""

from __future__ import annotations

from kraddr.geo.dto.admin import ConsistencyCaseDefinition

CASE_DEFINITIONS: tuple[ConsistencyCaseDefinition, ...] = (
    ConsistencyCaseDefinition(
        code="C1",
        name="텍스트에만 존재하는 BD_MGT_SN",
        compares="tl_juso_text 텍스트 정본과 tl_spbd_buld_polygon 건물 polygon natural key",
        abnormal_criteria="텍스트 정본에는 있으나 같은 natural key의 건물 polygon 행이 없다.",
        evidence=("bd_mgt_sn", "rncode_full", "건물번호", "bjd_cd", "주변 polygon 후보"),
        likely_causes=(
            "SHP 누락",
            "기준월 차이",
            "natural key 해소 실패",
            "건물 삭제/신규 반영 시차",
        ),
        decision_guide="기준월 차이면 defer, 반복 원천 누락이면 approve, loader key 오류면 reject",
        threshold="위반 1건 이상 WARN",
    ),
    ConsistencyCaseDefinition(
        code="C2",
        name="SHP polygon에만 존재하는 BD_MGT_SN",
        compares="SHP 건물 polygon과 텍스트 정본 natural key",
        abnormal_criteria="polygon에는 있으나 텍스트 정본에 대응 행이 없다.",
        evidence=("polygon 속성", "missing_resolve_key/missing_text", "주변 텍스트 후보"),
        likely_causes=("SHP 속성 결측", "정본 누락", "기준월 차이", "natural key 조합 오류"),
        decision_guide="missing_resolve_key는 reject 우선, 명백한 원천 시차는 defer",
        threshold="위반 1건 이상 ERROR",
    ),
    ConsistencyCaseDefinition(
        code="C3",
        name="대표 출입구가 해소되지 않은 건물",
        compares="텍스트 정본 건물과 대표 출입구(locsum, same-month direct entrance)",
        abnormal_criteria="대표 출입구 후보가 해소되지 않는다.",
        evidence=("텍스트 주소 key", "출입구 후보 여부", "source_kind", "source_yyyymm"),
        likely_causes=("위치정보요약DB 누락", "direct 출입구 기준월 불일치", "키 해소 실패"),
        decision_guide="source set 혼합이면 defer, 키 해소 규칙 문제면 reject",
        threshold="5% 초과 WARN, 그 이하는 INFO",
    ),
    ConsistencyCaseDefinition(
        code="C4",
        name="출입구 좌표와 건물 polygon 거리 이상치",
        compares="대표 출입구 좌표와 건물 polygon",
        abnormal_criteria="출입구와 nearest polygon 거리가 50m를 초과한다. 500m 초과는 ERROR다.",
        evidence=("출입구 점", "건물 polygon", "거리", "source_kind", "nearest polygon"),
        likely_causes=("좌표 원천 이상치", "잘못된 polygon 매칭", "기준월 차이", "좌표계 오류"),
        decision_guide="500m 초과는 reject 우선, 실제 원천 좌표 이상이면 approve와 근거 메모",
        threshold="50m 초과 WARN, 500m 초과 ERROR",
    ),
    ConsistencyCaseDefinition(
        code="C5",
        name="내비 centroid와 건물 polygon centroid 거리 이상치",
        compares="내비 centroid와 건물 polygon centroid",
        abnormal_criteria="centroid 간 거리가 10m를 초과한다.",
        evidence=("내비 centroid", "polygon centroid", "거리", "건물 속성"),
        likely_causes=("내비 centroid 편차", "polygon 후보 다대다", "기준월 차이"),
        decision_guide="도형이 복잡한 대형 건물은 approve, key mismatch는 reject",
        threshold="10m 초과 WARN",
    ),
    ConsistencyCaseDefinition(
        code="C6",
        name="우편번호 텍스트와 기초구역 polygon 불일치",
        compares="텍스트 우편번호와 기초구역 polygon",
        abnormal_criteria="우편번호 polygon이 없거나 출입구 좌표가 해당 polygon 밖에 있다.",
        evidence=("출입구 점", "BAS polygon", "zip_no", "bas_id"),
        likely_causes=("우편번호 원천 시차", "BAS polygon 누락", "좌표 오차"),
        decision_guide="polygon 누락은 defer, 좌표 외부는 지도 확인 후 approve 또는 reject",
        threshold="zip_no polygon 누락 WARN, 좌표 외부 ERROR",
    ),
    ConsistencyCaseDefinition(
        code="C7",
        name="행정구역 polygon과 출입구 좌표 불일치",
        compares="행정구역 polygon과 출입구 좌표",
        abnormal_criteria="행정 polygon이 없거나 출입구 좌표가 해당 polygon 밖에 있다.",
        evidence=("출입구 점", "법정동/행정동 polygon", "bjd_cd", "adm_cd"),
        likely_causes=("행정경계 변경 시차", "좌표 오차", "코드 매핑 오류"),
        decision_guide="경계 인접 소수는 approve, 코드/좌표 체계 오류는 reject",
        threshold="polygon 누락 WARN, 좌표 외부 ERROR",
    ),
    ConsistencyCaseDefinition(
        code="C8",
        name="도로명 폴리라인과 출입구 좌표 인접성 불일치",
        compares="도로명 polyline과 출입구 좌표",
        abnormal_criteria="같은 도로명의 도로 중심선 100m 안에 출입구가 없다.",
        evidence=("출입구 점", "도로 polyline", "거리", "rncode_full"),
        likely_causes=("도로 중심선 누락", "도로명 코드 매핑 오류", "대규모 단지 진입로"),
        decision_guide="실제 진입로가 멀면 approve, 코드 mismatch면 reject",
        threshold="같은 도로명 100m 밖 WARN",
    ),
    ConsistencyCaseDefinition(
        code="C9",
        name="PNU 형식 오류",
        compares="PNU 원문과 법정 PNU 자리수/산 여부 규칙",
        abnormal_criteria="PNU가 19자리가 아니거나 산 여부 자리가 1/2가 아니다.",
        evidence=("PNU 원문", "자리수", "bjd_cd", "산 여부", "본번/부번"),
        likely_causes=("파싱/적재 오류", "원천 값 결측", "원천 형식 변경"),
        decision_guide="대부분 loader/parser 결함 후보로 reject",
        threshold="위반 1건 이상 ERROR",
    ),
    ConsistencyCaseDefinition(
        code="C10",
        name="텍스트/SHP 적재 기준월 불일치",
        compares="원천별 source_yyyymm",
        abnormal_criteria="참여 원천의 기준월이 2종 이상이다.",
        evidence=("table별 기준월", "source set", "row_count", "manifest evidence"),
        likely_causes=("의도한 혼합 적재", "일부 원천 최신화", "다른 월 파일 혼입"),
        decision_guide="확인된 혼합은 approve, 확인 없는 혼합은 reject 또는 defer",
        threshold="기준월 2종 이상 WARN",
    ),
)

CASE_DEFINITION_BY_CODE = {case.code: case for case in CASE_DEFINITIONS}
