"""한국 주소 정보 API와 데이터 적재를 다루는 공개 진입점."""

from __future__ import annotations

from .client import AsyncKrAddrClient, KrAddrClient
from .data import (
    ROAD_NAME_KOREAN_DETAIL_SN,
    AsyncRoadNameAddressDataClient,
    RoadNameAddressDataClient,
    archive_standard_date,
    iter_related_jibun_records,
    iter_road_name_address_records,
    load_related_jibun_records,
    load_road_name_address_records,
)
from .dto import (
    CoordinateCandidate,
    KRMoisAddressProbe,
    KRMoisAddressValidationResult,
    PostalCodeLookupRequest,
    VWorldLikeGeocodeRequest,
    VWorldLikeReverseGeocodeRequest,
)
from .exceptions import (
    KrAddrAuthError,
    KrAddrError,
    KrAddrNoDataError,
    KrAddrParseError,
    KrAddrRateLimitError,
    KrAddrRequestError,
    KrAddrServerError,
)
from .fixtures import save_fixture, slugify
from .legal_dong import (
    DATA_GO_KR_LEGAL_DONG_PAGE_URL,
    AsyncDataGoKrLegalDongClient,
    DataGoKrLegalDongClient,
    iter_legal_dong_records,
    load_legal_dong_records,
    records_from_openapi_rows,
)
from .models import (
    AddressCoordinate,
    AddressSearchResult,
    DatasetFile,
    DetailAddress,
    EnglishAddressSearchResult,
    JusoPage,
    LegalDongRecord,
    RelatedJibunRecord,
    RoadNameAddressKoreanRecord,
)
from .reverse import (
    NavigationBuildingRecord,
    ReverseGeocoder,
    ReverseGeocodeResult,
    VWorldReverseGeocoder,
    iter_navigation_building_records,
    load_navigation_building_records,
)
from .spatialite import (
    BoundarySpatialiteLoadResult,
    LocationSummaryEntranceRecord,
    NavigationRoadSectionEntranceRecord,
    SpatialiteAddressStore,
    SpatialiteLoadResult,
    boundary_level_from_path,
    iter_location_summary_records,
    iter_navigation_road_section_entrance_records,
    make_spatialite_metadata,
    read_boundary_zip,
)
from .store import RoadNameAddressStore

JusoClient = KrAddrClient

__all__ = [
    "AddressCoordinate",
    "AddressSearchResult",
    "AsyncDataGoKrLegalDongClient",
    "AsyncKrAddrClient",
    "AsyncRoadNameAddressDataClient",
    "BoundarySpatialiteLoadResult",
    "CoordinateCandidate",
    "DATA_GO_KR_LEGAL_DONG_PAGE_URL",
    "DataGoKrLegalDongClient",
    "DatasetFile",
    "DetailAddress",
    "EnglishAddressSearchResult",
    "JusoClient",
    "JusoPage",
    "KRMoisAddressProbe",
    "KRMoisAddressValidationResult",
    "KrAddrAuthError",
    "KrAddrClient",
    "KrAddrError",
    "KrAddrNoDataError",
    "KrAddrParseError",
    "KrAddrRateLimitError",
    "KrAddrRequestError",
    "KrAddrServerError",
    "LegalDongRecord",
    "LocationSummaryEntranceRecord",
    "NavigationBuildingRecord",
    "NavigationRoadSectionEntranceRecord",
    "PostalCodeLookupRequest",
    "ROAD_NAME_KOREAN_DETAIL_SN",
    "RelatedJibunRecord",
    "ReverseGeocodeResult",
    "ReverseGeocoder",
    "RoadNameAddressDataClient",
    "RoadNameAddressKoreanRecord",
    "RoadNameAddressStore",
    "read_boundary_zip",
    "save_fixture",
    "slugify",
    "SpatialiteAddressStore",
    "SpatialiteLoadResult",
    "VWorldLikeGeocodeRequest",
    "VWorldLikeReverseGeocodeRequest",
    "VWorldReverseGeocoder",
    "archive_standard_date",
    "boundary_level_from_path",
    "iter_related_jibun_records",
    "iter_legal_dong_records",
    "iter_navigation_building_records",
    "iter_location_summary_records",
    "iter_navigation_road_section_entrance_records",
    "iter_road_name_address_records",
    "load_legal_dong_records",
    "load_navigation_building_records",
    "load_related_jibun_records",
    "load_road_name_address_records",
    "make_spatialite_metadata",
    "records_from_openapi_rows",
]
